### ISSUE TITLE
warning in Ipums_SOIAA_2018 

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/DCOLA#17]
We get WARNING: Unknown place of birth _N_=227122 bpld=Maryland/Indochina/District of Columbia...for some observations but non of them are our birthplace of interest.  I'm not sure how to fix that or if it matters at all for our tables? @ptatian  cc @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 It probably does not matter if they are not places of interest. What part of the code is producing this warning? The most important thing is that the latino, asianpi, and african vars have the correct countries assigned to them. @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 I didn't fully appreciate the extent of this problem, since I couldn't review the LOG. There were many observations with this warning and they included South Korea and other countries that should be included in the analysis. The problem was that in the workbook I sent there were some hidden rows that included codes for 2000. Since you listed the Asian country codes individually, the hidden codes got omitted. I'm fixing the problem now.
